# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  default:
    desc: List all available commands
    cmd: task --list-all

  ci:
    desc: Run full CI pipeline (format, test, lint)
    cmds:
      - task: format
      - task: lint
      - task: test

  format:
    desc: Run formatter
    cmd: golangci-lint fmt ./...

  lint:
    desc: Run liter
    cmd: golangci-lint run ./...

  test:
    desc: Run tests
    cmd: go test ./...
